### ISSUE TITLE
Error in GhprTestExecutionEngine.OnScenarioEnd when running Specflow tests in parallel

### ISSUE THREAD

**Issue by lendlegiovanni** [GHPReporter/Ghpr.SpecFlow#11]
SpecflowException was encountered in line #99 in GhprTestExecutionEngine.cs when we execute the specflow tests in parallel. The reason behind this is Ghpr is trying to access a static property (ScenarioContext.Current). Can this be implemented the same way you implemented the FeatureInfo?

Thank you.

**Comment by elv1s42** [comment]
Hi @lendlegiovanni 

I will try to reproduce this issue. 
But I think I know how to fix it:
![2017-04-18 12_47_17-github](https://cloud.githubusercontent.com/assets/6689884/25124703/35b38824-2435-11e7-851a-9cc27761f42f.png)

**Comment by lendlegiovanni** [comment]
Thanks @elv1s42!

**Comment by elv1s42** [comment]
@lendlegiovanni , before making release with possible fix I wanted to test it first. 
How are you running your tests in parallel? Do you use NUnit v3 for it (https://github.com/techtalk/SpecFlow/wiki/Parallel-Execution#notes-for-nunit-v3-support)?

**Comment by lendlegiovanni** [comment]
@elv1s42, yes we're using nunit v3.

**Comment by elv1s42** [comment]
Good, I will try to reproduce this issue using NUnit v3.
Thanks!

**Comment by lendlegiovanni** [comment]
Hi @elv1s42, If you need some help in setting up a specflow project for the testing, I can create one for you. Thank you!

**Comment by elv1s42** [comment]
Hi @lendlegiovanni , thank you. I have examples repository that is used for testing. I've added `[assembly: Parallelizable(ParallelScope.Fixtures)]` attribute:
https://github.com/GHPReporter/Ghpr.SpecFlow.Examples/blob/master/Ghpr.SpecFlow.Examples/Ghpr.SpecFlow.ParallelExamples/Properties/AssemblyInfo.cs

But there are some problems with getting test output when tests are running in parallel, here is discussion: https://github.com/techtalk/SpecFlow/issues/750

**Comment by elv1s42** [comment]
Hi @lendlegiovanni, parallel test execution should work fine now, new version is released.
However, there is still one issue with getting test output for tests running in parallel. I raised an issue regarding this question: https://github.com/techtalk/SpecFlow/issues/842

In any cas, you can use this plugin or you can try NUnit3 Console extension (because SpecFlow tests are still NUnit3 tests too).

There is another workaroud that can be implemented in the future. it is possible to store log messages inside Scenario Context like this: `var log = (Log)ScenarioContext.Current[ScenarioLogKey];`
