### ISSUE TITLE
Images saved with Ghpr.Core.Helpers.ScreenshotHelper.SaveScreenshot() not appearing in report

### ISSUE THREAD

**Issue by gareth-cheeseman** [GHPReporter/Ghpr.SpecFlow#13]
The images are saved where I expect, but are not picked up in the ghpreport.

I'm using specflow with selenium webdriver. And have installed the ghpr specflow plugin from nuget. I've implemented the following screenshot method:

```
        public static void CreateScreenshot(IWebDriver driver)
        {
            string pathName = Configuration.Instance.ReportingFolder;
            Screenshot screen = ((ITakesScreenshot)driver).GetScreenshot();
            var bytes = screen.AsByteArray;
            DateTime date = new DateTime();
            Ghpr.Core.Helpers.ScreenshotHelper.SaveScreenshot(pathName, bytes, date);
        }
```
It is called in wrapper methods for selenium selecting methods such as
```
        public static void SendKeys(IWebDriver driver, By by, string valueToType, bool inputValidation = false)
        {
            try
            {
                new WebDriverWait(driver, TimeSpan.FromSeconds(Configuration.DefaultTimeout)).Until(ExpectedConditions.ElementIsVisible(by));
                driver.FindElement(by).Clear();
                driver.FindElement(by).SendKeys(valueToType);
            }
            catch (Exception ex) when (ex is NoSuchElementException || ex is WebDriverTimeoutException)
            {
                ReportingMethods.CreateScreenshot(driver);
                Assert.Fail(ex.ToString());
            }
}
```
And at the end of tests:
```
        [AfterScenario]
        public static void WrapUpReport()
        {
            switch (TestContext.CurrentContext.Result.Outcome.Status.ToString().ToLower())
            {
                case "passed":
                    ReportingMethods.CreateScreenshot(driver);
                    break;

                default:
                    break;
            }
```

**Comment by elv1s42** [comment]
Hi @gareth-cheeseman !
Thank you for submitting this issue.
I will create new feature file for testing and then try to reproduce this issue using your code.

**Comment by elv1s42** [comment]
Hi @gareth-cheeseman !
I have fixed this issue for SpecFlow, but only partially.

I have created very simple method to take screenshots: 
![image](https://user-images.githubusercontent.com/6689884/27682472-52431dc8-5ccb-11e7-9f52-109e4e411354.png)

Then I've added this method to one step: 
![image](https://user-images.githubusercontent.com/6689884/27682495-6a89d660-5ccb-11e7-86e8-ca0fd2411e42.png)

And it worked well. 
You can see the example in the [example repository](https://github.com/GHPReporter/Ghpr.SpecFlow.Examples/blob/master/Ghpr.SpecFlow.Examples/Ghpr.SpecFlow.Examples/Steps/BasicsSteps.cs#L55).

But the problem appeared with taking screenshot from `AfterScenario` method:
![image](https://user-images.githubusercontent.com/6689884/27682587-dfab23ae-5ccb-11e7-9684-92f9c2dd3872.png)

This screenshot does not appear in report because SpecFlow method `OnTestRunEnd` (this method is used to save information about test run in .json format for GHPReporter) was called **before** `AfterScenario` method.

So there is still some workaroud required for this issue.
